name: crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - .github/workflows/faux-crucible-ci.yaml
    - 'docs/**'
  workflow_dispatch:

jobs:
  crucible-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout packrat
      uses: actions/checkout@v2
      with:
        path: packrat

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "packrat"
        ci_target: "packrat"
        ci_target_dir: ${{ github.workspace }}/packrat
